### ISSUE TITLE
Multivariate2018_ts.zip doses not exist

### ISSUE THREAD

**Issue by Bestlzz** [Navidfoumani/ConvTran#7]
I just read your paper "Improving position encoding of transformers for multivariate time series classification",
I was very inspired. So, I ran the code you provided, but when I downloaded the data Multivariate2018_ts.zip, Found that you give the url "http://www.timeseriesclassification.com/Downloads/Archives/Multivariate2018_ts.zip" does not exist. I would appreciate it if you could help me with this problem.

**Comment by Navidfoumani** [comment]
Thank you for bringing this to my attention. It appears that the previous link for downloading the datasets has been updated. Here is the new link to download it: 
https://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip

**Comment by Bestlzz** [comment]
> Thank you for bringing this to my attention. It appears that the previous link for downloading the datasets has been updated. Here is the new link to download it: https://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip

Thank you for your reply！
